sudo: false

addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libzmq-dev

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - bash .travis_dependencies.sh
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        export PATH="$HOME/env/miniconda27/bin:$PATH";
      elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
        export PATH="$HOME/env/miniconda34/bin:$PATH";
      else
        export PATH="$HOME/env/miniconda35/bin:$PATH";
      fi
    - hash -r
    - source activate test-environment

install:
    - pip install coveralls
    - pip install git+https://github.com/ejhumphrey/biggie.git
    - pip install -e ./

script:
    - python --version
    - py.test -vs --cov=minibench minibench

after_success:
    - coveralls
    - pip uninstall -y minibench

after_failure:
    - pip uninstall -y minibench
