sudo: false

addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libzmq-dev
    - python-scipy
    - python3-scipy

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - pip install coveralls
    - pip install git+https://github.com/ejhumphrey/biggie.git
    - pip install -e ./

script:
    - python --version
    - py.test -vs minibench

after_success:
    - coveralls
    - pip uninstall -y minibench

after_failure:
    - pip uninstall -y minibench
